### ISSUE TITLE
Deploy a new dev instance for Canvas

### ISSUE THREAD

**Issue by Himanshul-Patel** [talview/canvas-lms#2]
We need to deploy a new dev instance for Canvas LMS

**Comment by Himanshul-Patel** [comment]
Devops ticket is created for deployment - https://github.com/talview/dev-cluster/issues/1406
Moving this to blocked till the above ticket is closed

**Comment by rohansharmasitoula** [comment]
Blocked by : https://github.com/talview/dev-cluster/issues/1480

**Comment by SeemaKhan3** [comment]
Verified this ticket - Working as expected 



![Image](https://github.com/talview/canvas-lms/assets/143271817/36338bb9-7063-4477-bb4c-b659d0076129)
